// ==UserScript==
// @name         Ek Biç Sula
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       Furkanlation
// @match        https://s1.tr.myfreefarm.com/main.php?ref=
// @icon         https://www.google.com/s2/favicons?sz=64&domain=myfreefarm.com
// @grant        none
// ==/UserScript==

(function() {
    function getElementByXpath(path) {

        return document.evaluate(path, document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue;

    }
    /* 	 */


    var x = document.createElement("BUTTON");
    var t = document.createTextNode("Sula Biç Topla");
    x.appendChild(t);
    document.body.appendChild(x);

    x.style.color = '#fff';
    x.style.background = "hsl(252deg 68% 59%)";
    x.style.padding = '19px';
    x.style.borderRadius = "25px";
    x.style.marginLeft = "77%";
    x.style.marginTop = "-36%";

    x.onclick = function(){
        var b1= getElementByXpath('//*[@id="b1"]');
        var b2= getElementByXpath('//*[@id="b2"]');
        var b3= getElementByXpath('//*[@id="b3"]');
        var b4= getElementByXpath('//*[@id="b4"]');
        var b5= getElementByXpath('//*[@id="b5"]');
        var b6= getElementByXpath('//*[@id="b6"]');
        var b7= getElementByXpath('//*[@id="b7"]');
        var b8= getElementByXpath('//*[@id="b8"]');
        var b9= getElementByXpath('//*[@id="b9"]');
        var b10= getElementByXpath('//*[@id="b10"]');
        var b11= getElementByXpath('//*[@id="b11"]');
        var b12= getElementByXpath('//*[@id="b12"]');
        var b13= getElementByXpath('//*[@id="b13"]');
        var b14= getElementByXpath('//*[@id="b14"]');
        var b15= getElementByXpath('//*[@id="b15"]');
        var b16= getElementByXpath('//*[@id="b16"]');
        var b17= getElementByXpath('//*[@id="b17"]');
        var b18= getElementByXpath('//*[@id="b18"]');
        var b19= getElementByXpath('//*[@id="b19"]');
        var b20= getElementByXpath('//*[@id="b20"]');
        var b21= getElementByXpath('//*[@id="b21"]');
        var b22= getElementByXpath('//*[@id="b22"]');
        var b23= getElementByXpath('//*[@id="b23"]');
        var b24= getElementByXpath('//*[@id="b24"]');
        var b25= getElementByXpath('//*[@id="b25"]');
        var b26= getElementByXpath('//*[@id="b26"]');
        var b27= getElementByXpath('//*[@id="b27"]');
        var b28= getElementByXpath('//*[@id="b28"]');
        var b29= getElementByXpath('//*[@id="b29"]');
        var b30= getElementByXpath('//*[@id="b30"]');
        var b31= getElementByXpath('//*[@id="b31"]');
        var b32= getElementByXpath('//*[@id="b32"]');
        var b33= getElementByXpath('//*[@id="b33"]');
        var b34= getElementByXpath('//*[@id="b34"]');
        var b35= getElementByXpath('//*[@id="b35"]');
        var b36= getElementByXpath('//*[@id="b36"]');
        var b37= getElementByXpath('//*[@id="b37"]');
        var b38= getElementByXpath('//*[@id="b38"]');
        var b39= getElementByXpath('//*[@id="b39"]');
        var b40= getElementByXpath('//*[@id="b40"]');
        var b41= getElementByXpath('//*[@id="b41"]');
        var b42= getElementByXpath('//*[@id="b42"]');
        var b43= getElementByXpath('//*[@id="b43"]');
        var b44= getElementByXpath('//*[@id="b44"]');
        var b45= getElementByXpath('//*[@id="b45"]');
        var b46= getElementByXpath('//*[@id="b46"]');
        var b47= getElementByXpath('//*[@id="b47"]');
        var b48= getElementByXpath('//*[@id="b48"]');
        var b49= getElementByXpath('//*[@id="b49"]');
        var b50= getElementByXpath('//*[@id="b50"]');
        var b51= getElementByXpath('//*[@id="b51"]');
        var b52= getElementByXpath('//*[@id="b52"]');
        var b53= getElementByXpath('//*[@id="b53"]');
        var b54= getElementByXpath('//*[@id="b54"]');
        var b55= getElementByXpath('//*[@id="b55"]');
        var b56= getElementByXpath('//*[@id="b56"]');
        var b57= getElementByXpath('//*[@id="b57"]');
        var b58= getElementByXpath('//*[@id="b58"]');
        var b59= getElementByXpath('//*[@id="b59"]');
        var b60= getElementByXpath('//*[@id="b60"]');
        var b61= getElementByXpath('//*[@id="b61"]');
        var b62= getElementByXpath('//*[@id="b62"]');
        var b63= getElementByXpath('//*[@id="b63"]');
        var b64= getElementByXpath('//*[@id="b64"]');
        var b65= getElementByXpath('//*[@id="b65"]');
        var b66= getElementByXpath('//*[@id="b66"]');
        var b67= getElementByXpath('//*[@id="b67"]');
        var b68= getElementByXpath('//*[@id="b68"]');
        var b69= getElementByXpath('//*[@id="b69"]');
        var b70= getElementByXpath('//*[@id="b70"]');
        var b71= getElementByXpath('//*[@id="b71"]');
        var b72= getElementByXpath('//*[@id="b72"]');
        var b73= getElementByXpath('//*[@id="b73"]');
        var b74= getElementByXpath('//*[@id="b74"]');
        var b75= getElementByXpath('//*[@id="b75"]');
        var b76= getElementByXpath('//*[@id="b76"]');
        var b77= getElementByXpath('//*[@id="b77"]');
        var b78= getElementByXpath('//*[@id="b78"]');
        var b79= getElementByXpath('//*[@id="b79"]');
        var b80= getElementByXpath('//*[@id="b80"]');
        var b81= getElementByXpath('//*[@id="b81"]');
        var b82= getElementByXpath('//*[@id="b82"]');
        var b83= getElementByXpath('//*[@id="b83"]');
        var b84= getElementByXpath('//*[@id="b84"]');
        var b85= getElementByXpath('//*[@id="b85"]');
        var b86= getElementByXpath('//*[@id="b86"]');
        var b87= getElementByXpath('//*[@id="b87"]');
        var b88= getElementByXpath('//*[@id="b88"]');
        var b89= getElementByXpath('//*[@id="b89"]');
        var b90= getElementByXpath('//*[@id="b90"]');
        var b91= getElementByXpath('//*[@id="b91"]');
        var b92= getElementByXpath('//*[@id="b92"]');
        var b93= getElementByXpath('//*[@id="b93"]');
        var b94= getElementByXpath('//*[@id="b94"]');
        var b95= getElementByXpath('//*[@id="b95"]');
        var b96= getElementByXpath('//*[@id="b96"]');
        var b97= getElementByXpath('//*[@id="b97"]');
        var b98= getElementByXpath('//*[@id="b98"]');
        var b99= getElementByXpath('//*[@id="b99"]');
        var b100= getElementByXpath('//*[@id="b100"]');
        var b101= getElementByXpath('//*[@id="b101"]');
        var b102= getElementByXpath('//*[@id="b102"]');
        var b103= getElementByXpath('//*[@id="b103"]');
        var b104= getElementByXpath('//*[@id="b104"]');
        var b105= getElementByXpath('//*[@id="b105"]');
        var b106= getElementByXpath('//*[@id="b106"]');
        var b107= getElementByXpath('//*[@id="b107"]');
        var b108= getElementByXpath('//*[@id="b108"]');
        var b109= getElementByXpath('//*[@id="b109"]');
        var b110= getElementByXpath('//*[@id="b110"]');
        var b111= getElementByXpath('//*[@id="b111"]');
        var b112= getElementByXpath('//*[@id="b112"]');
        var b113= getElementByXpath('//*[@id="b113"]');
        var b114= getElementByXpath('//*[@id="b114"]');
        var b115= getElementByXpath('//*[@id="b115"]');
        var b116= getElementByXpath('//*[@id="b116"]');
        var b117= getElementByXpath('//*[@id="b117"]');
        var b118= getElementByXpath('//*[@id="b118"]');
        var b119= getElementByXpath('//*[@id="b119"]');
        var b120= getElementByXpath('//*[@id="b120"]');

        b1.click();
        b2.click();
        b3.click();
        b4.click();
        b5.click();
        b6.click();
        b7.click();
        b8.click();
        b9.click();
        b10.click();
        b11.click();
        b12.click();
        b13.click();
        b14.click();
        b15.click();
        b16.click();
        b17.click();
        b18.click();
        b19.click();
        b20.click();
        b21.click();
        b22.click();
        b23.click();
        b24.click();
        b25.click();
        b26.click();
        b27.click();
        b28.click();
        b29.click();
        b30.click();
        b31.click();
        b32.click();
        b33.click();
        b34.click();
        b35.click();
        b36.click();
        b37.click();
        b38.click();
        b39.click();
        b40.click();
        b41.click();
        b42.click();
        b43.click();
        b44.click();
        b45.click();
        b46.click();
        b47.click();
        b48.click();
        b49.click();
        b50.click();
        b51.click();
        b52.click();
        b53.click();
        b54.click();
        b55.click();
        b56.click();
        b57.click();
        b58.click();
        b59.click();
        b60.click();
        b61.click();
        b62.click();
        b63.click();
        b64.click();
        b65.click();
        b66.click();
        b67.click();
        b68.click();
        b69.click();
        b70.click();
        b71.click();
        b72.click();
        b73.click();
        b74.click();
        b75.click();
        b76.click();
        b77.click();
        b78.click();
        b79.click();
        b80.click();
        b81.click();
        b82.click();
        b83.click();
        b84.click();
        b85.click();
        b86.click();
        b87.click();
        b88.click();
        b89.click();
        b90.click();
        b91.click();
        b92.click();
        b93.click();
        b94.click();
        b95.click();
        b96.click();
        b97.click();
        b98.click();
        b99.click();
        b100.click();
        b101.click();
        b102.click();
        b103.click();
        b104.click();
        b105.click();
        b106.click();
        b107.click();
        b108.click();
        b109.click();
        b110.click();
        b111.click();
        b112.click();
        b113.click();
        b114.click();
        b115.click();
        b116.click();
        b117.click();
        b118.click();
        b119.click();
        b120.click();
    };
})();